### ISSUE TITLE
Plugin construction/init

### ISSUE THREAD

**Issue by billtomczak** [OSTraining/AllediaFramework#6]
The [init method](https://github.com/OSTraining/AllediaFramework/blob/master/src/Framework/Joomla/Extension/AbstractPlugin.php#L55) in AbstractPlugin is never called. Did you mean to leave it to subclasses to call? If so then the empty [__construct()  method](https://github.com/OSTraining/AllediaFramework/blob/master/src/Framework/Joomla/Extension/AbstractPlugin.php#L43) should be removed.

**Comment by andergmartins** [comment]
Yes, the subclass should be able if it wants or not to init that. I was thinking about the cases where we check a conditional before really trigger the plugin, like some system plugins where we check if we are on the right page/route before execute the plugin stuff. Otherwise it would load all the internal data for all requests, even the cases where that is not required.

**Comment by billtomczak** [comment]
cool. That makes sense. So we can get rid of the empty __construct() method.

**Comment by andergmartins** [comment]
Yes, agreed

**Comment by andergmartins** [comment]
Thanks @billtomczak
